name: 'Require Reviewers'
description: ''
author: 'GitHub'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
  configuration-path:
    description: 'The path for the configurations'
    default: '.github/labeler.yml'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'