name: Licensed

on:
  # run on pushes to the default branch
  push:
    branches:
      - main
  # run on pull request events with changes to code
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  # run on demand
  workflow_dispatch:

# ensure that the action can push changes to the repo and edit PRs
# when using `secrets.GITHUB_TOKEN`
permissions:
  pull-requests: write
  contents: write

jobs:
  licensed:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: jonabc/setup-licensed@v1
      with:
        version: 3.x
    - run: npm install # install your projects dependencies in local environment
    - id: licensed
      uses: jonabc/licensed-ci@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/github-script@0.2.0
      if: always() && steps.licensed.outputs.pr_number
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.issues.createComment({
            ...context.repo,
            issue_number: ${{ steps.licensed.outputs.pr_number }}
            body: 'My custom PR message'
          })